'use client'

interface IndustriesDropdownProps {
  selectedIndustry: string
  onIndustryChange: (industry: string) => void
  className?: string
}

const industries = [
  'Technology & Software',
  'Healthcare & Medical',
  'Finance & Banking',
  'Insurance',
  'Real Estate',
  'Construction & Engineering',
  'Manufacturing',
  'Retail & E-commerce',
  'Food & Beverage',
  'Hospitality & Tourism',
  'Transportation & Logistics',
  'Energy & Utilities',
  'Education & Training',
  'Media & Entertainment',
  'Telecommunications',
  'Agriculture & Farming',
  'Mining & Natural Resources',
  'Chemicals & Materials',
  'Pharmaceuticals & Biotechnology',
  'Automotive & Aerospace',
  'Consumer Goods',
  'Fashion & Apparel',
  'Sports & Recreation',
  'Non-profit & Social Services',
  'Government & Public Sector',
  'Legal Services',
  'Consulting & Professional Services',
  'Marketing & Advertising',
  'Design & Creative Services',
  'Environmental Services',
  'Waste Management',
  'Security & Safety',
  'Human Resources',
  'Information Technology Services',
  'Cloud Computing',
  'Artificial Intelligence & Machine Learning',
  'Blockchain & Cryptocurrency',
  'Cybersecurity',
  'Data Analytics & Business Intelligence',
  'Digital Marketing',
  'E-learning & EdTech',
  'FinTech',
  'HealthTech',
  'InsurTech',
  'PropTech',
  'CleanTech & Renewable Energy',
  'Biotechnology',
  'Nanotechnology',
  'Robotics & Automation',
  'Virtual Reality & Augmented Reality',
  'Internet of Things (IoT)',
  'Gaming & Esports',
  'Streaming & Digital Media',
  'Social Media & Networking',
  'E-commerce Platforms',
  'Marketplaces',
  'SaaS (Software as a Service)',
  'PaaS (Platform as a Service)',
  'IaaS (Infrastructure as a Service)',
  'Mobile Applications',
  'Web Development',
  'UI/UX Design',
  'Product Management',
  'Project Management',
  'Quality Assurance & Testing',
  'DevOps & Infrastructure',
  'Cloud Architecture',
  'Network Security',
  'Data Science',
  'Machine Learning Engineering',
  'Software Engineering',
  'Full Stack Development',
  'Frontend Development',
  'Backend Development',
  'Mobile Development',
  'Game Development',
  'Blockchain Development',
  'Artificial Intelligence Research',
  'Data Engineering',
  'Business Analysis',
  'System Administration',
  'Database Administration',
  'Network Administration',
  'IT Support',
  'Technical Writing',
  'Digital Transformation',
  'Business Intelligence',
  'Data Visualization',
  'Predictive Analytics',
  'Natural Language Processing',
  'Computer Vision',
  'Robotics Process Automation',
  'Smart Manufacturing',
  'Industrial IoT',
  'Supply Chain Management',
  'Inventory Management',
  'Warehouse Management',
  'Cold Chain Logistics',
  'Last Mile Delivery',
  'Freight & Shipping',
  'Air Cargo',
  'Maritime Shipping',
  'Rail Transportation',
  'Public Transportation',
  'Ride Sharing & Mobility',
  'Electric Vehicles',
  'Autonomous Vehicles',
  'Aviation',
  'Space Technology',
  'Satellite Communications',
  'GPS & Navigation',
  'Geospatial Technology',
  'Weather Forecasting',
  'Climate Technology',
  'Carbon Capture & Storage',
  'Water Treatment',
  'Air Quality Management',
  'Noise Pollution Control',
  'Sustainable Development',
  'Green Building',
  'Smart Cities',
  'Urban Planning',
  'Architecture',
  'Interior Design',
  'Landscape Architecture',
  'Civil Engineering',
  'Mechanical Engineering',
  'Electrical Engineering',
  'Chemical Engineering',
  'Biomedical Engineering',
  'Aerospace Engineering',
  'Nuclear Engineering',
  'Petroleum Engineering',
  'Mining Engineering',
  'Materials Science',
  'Physics Research',
  'Chemistry Research',
  'Biology Research',
  'Medical Research',
  'Clinical Research',
  'Pharmaceutical Research',
  'Genetic Engineering',
  'Stem Cell Research',
  'Neuroscience',
  'Psychology',
  'Mental Health Services',
  'Counseling & Therapy',
  'Social Work',
  'Community Development',
  'Public Health',
  'Epidemiology',
  'Healthcare Administration',
  'Hospital Management',
  'Medical Devices',
  'Diagnostic Equipment',
  'Surgical Instruments',
  'Medical Supplies',
  'Healthcare IT',
  'Electronic Health Records',
  'Telemedicine',
  'Remote Patient Monitoring',
  'Wellness & Fitness',
  'Nutrition & Dietetics',
  'Alternative Medicine',
  'Veterinary Services',
  'Animal Health',
  'Pet Care',
  'Wildlife Conservation',
  'Environmental Conservation',
  'Forestry',
  'Fisheries',
  'Aquaculture',
  'Horticulture',
  'Floriculture',
  'Organic Farming',
  'Sustainable Agriculture',
  'Precision Agriculture',
  'AgriTech',
  'Food Processing',
  'Beverage Production',
  'Food Safety',
  'Quality Control',
  'Food Technology',
  'Nutritional Science',
  'Culinary Arts',
  'Restaurant Management',
  'Hotel Management',
  'Event Management',
  'Tourism Services',
  'Travel Agencies',
  'Airline Services',
  'Cruise Lines',
  'Timeshare & Vacation Rentals',
  'Business Travel',
  'Corporate Travel Management',
  'Travel Technology',
  'Booking Platforms',
  'Review Platforms',
  'Travel Insurance',
  'Currency Exchange',
  'International Trade',
  'Import/Export',
  'Customs Brokerage',
  'Trade Finance',
  'Commodities Trading',
  'Stock Market',
  'Investment Banking',
  'Asset Management',
  'Wealth Management',
  'Private Equity',
  'Venture Capital',
  'Angel Investing',
  'Crowdfunding',
  'Peer-to-Peer Lending',
  'Microfinance',
  'Islamic Banking',
  'Digital Banking',
  'Mobile Banking',
  'Online Payments',
  'Cryptocurrency Exchanges',
  'Digital Wallets',
  'Buy Now Pay Later',
  'Point of Sale Systems',
  'Payment Processing',
  'Merchant Services',
  'Fraud Detection',
  'Risk Management',
  'Compliance',
  'Audit & Assurance',
  'Tax Services',
  'Bookkeeping',
  'Payroll Services',
  'Corporate Finance',
  'Mergers & Acquisitions',
  'Initial Public Offerings',
  'Corporate Governance',
  'Investor Relations',
  'Shareholder Services',
  'Dividend Management',
  'Stock Transfer',
  'Proxy Voting',
  'Annual Reports',
  'Financial Planning',
  'Retirement Planning',
  'Estate Planning',
  'Tax Planning',
  'Insurance Planning',
  'Risk Assessment',
  'Underwriting',
  'Claims Processing',
  'Loss Adjustment',
  'Actuarial Services',
  'Reinsurance',
  'Insurance Brokerage',
  'Insurance Technology',
  'Health Insurance',
  'Life Insurance',
  'Property Insurance',
  'Casualty Insurance',
  'Liability Insurance',
  'Professional Indemnity',
  'Directors & Officers Insurance',
  'Cyber Insurance',
  'Political Risk Insurance',
  'Trade Credit Insurance',
  'Marine Insurance',
  'Aviation Insurance',
  'Construction Insurance',
  'Product Liability Insurance',
  'Environmental Liability Insurance',
  'Workers Compensation',
  'Disability Insurance',
  'Long-term Care Insurance',
  'Pet Insurance',
  'Wedding Insurance',
  'Event Insurance',
  'Rental Insurance',
  'Mortgage Insurance',
  'Title Insurance',
  'Flood Insurance',
  'Earthquake Insurance',
  'Terrorism Insurance',
  'Kidnap & Ransom Insurance'
]

export default function IndustriesDropdown({ selectedIndustry, onIndustryChange, className = '' }: IndustriesDropdownProps) {
  return (
    <div className={className}>
      <label className="block text-sm font-medium text-gray-700 mb-1">
        Industry
      </label>
      <select
        className="w-full p-3 rounded-xl border border-gray-300 focus:ring-2 focus:ring-amber-400 focus:border-transparent"
        value={selectedIndustry}
        onChange={(e) => onIndustryChange(e.target.value)}
      >
        <option value="">Select an industry</option>
        {industries.map((industry) => (
          <option key={industry} value={industry}>
            {industry}
          </option>
        ))}
      </select>
    </div>
  )
}
